/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Macros = IDL.Record({
  'fatG' : IDL.Nat,
  'calories' : IDL.Nat,
  'carbsG' : IDL.Nat,
  'proteinG' : IDL.Nat,
});
export const MealType = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snack' : IDL.Null,
  'dinner' : IDL.Null,
});
export const Meal = IDL.Record({
  'prepTimeMins' : IDL.Nat,
  'name' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'macros' : Macros,
  'servings' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
  'mealType' : MealType,
});
export const Exercise = IDL.Record({
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'description' : IDL.Text,
  'instructions' : IDL.Text,
  'durationSec' : IDL.Nat,
});
export const DayPlan = IDL.Record({
  'day' : IDL.Nat,
  'focus' : IDL.Text,
  'meals' : IDL.Vec(Meal),
  'title' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
});
export const DateKey = IDL.Text;
export const Timestamp = IDL.Int;
export const WaterEntry = IDL.Record({
  'amountMl' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const DailyTrackingSummary = IDL.Record({
  'date' : DateKey,
  'lastUpdated' : Timestamp,
  'waterEntries' : IDL.Vec(WaterEntry),
  'steps' : IDL.Nat,
  'totalWaterMl' : IDL.Nat,
  'waterGoalMl' : IDL.Nat,
});
export const FlexibilityLevel = IDL.Nat;
export const FitnessTrack = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'principal' : IDL.Principal,
  'heightCm' : IDL.Float64,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'weightKg' : IDL.Float64,
  'flexibilityLevel' : FlexibilityLevel,
  'dietaryRestrictions' : IDL.Text,
  'fitnessTrack' : FitnessTrack,
  'phone' : IDL.Text,
  'healthIssues' : IDL.Text,
});
export const UserProgress = IDL.Record({
  'completedDays' : IDL.Vec(IDL.Nat),
  'principal' : IDL.Principal,
  'lastCompletedDay' : IDL.Opt(IDL.Nat),
  'fitnessTrack' : FitnessTrack,
  'isDeveloper' : IDL.Bool,
});
export const DailyStepCount = IDL.Record({
  'date' : DateKey,
  'lastUpdated' : Timestamp,
  'steps' : IDL.Nat,
});
export const ProfileInput = IDL.Record({
  'age' : IDL.Nat,
  'heightCm' : IDL.Float64,
  'email' : IDL.Text,
  'weightKg' : IDL.Float64,
  'flexibilityLevel' : FlexibilityLevel,
  'dietaryRestrictions' : IDL.Text,
  'phone' : IDL.Text,
  'healthIssues' : IDL.Text,
});

export const idlService = IDL.Service({
  'addWaterEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'clearLastWaterEntry' : IDL.Func([IDL.Text], [], []),
  'getAllDayPlans' : IDL.Func([], [IDL.Vec(DayPlan)], ['query']),
  'getDailyTrackingSummary' : IDL.Func(
      [IDL.Text],
      [DailyTrackingSummary],
      ['query'],
    ),
  'getDayPlan' : IDL.Func([IDL.Nat], [IDL.Opt(DayPlan)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyProgress' : IDL.Func([], [UserProgress], ['query']),
  'getStepCount' : IDL.Func([IDL.Text], [DailyStepCount], ['query']),
  'getWaterIntake' : IDL.Func([IDL.Text], [DailyTrackingSummary], ['query']),
  'hasCompletedOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
  'markDayComplete' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveProfile' : IDL.Func([ProfileInput], [UserProfile], []),
  'saveStepCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setDeveloperMode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Macros = IDL.Record({
    'fatG' : IDL.Nat,
    'calories' : IDL.Nat,
    'carbsG' : IDL.Nat,
    'proteinG' : IDL.Nat,
  });
  const MealType = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const Meal = IDL.Record({
    'prepTimeMins' : IDL.Nat,
    'name' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'macros' : Macros,
    'servings' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
    'mealType' : MealType,
  });
  const Exercise = IDL.Record({
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'description' : IDL.Text,
    'instructions' : IDL.Text,
    'durationSec' : IDL.Nat,
  });
  const DayPlan = IDL.Record({
    'day' : IDL.Nat,
    'focus' : IDL.Text,
    'meals' : IDL.Vec(Meal),
    'title' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
  });
  const DateKey = IDL.Text;
  const Timestamp = IDL.Int;
  const WaterEntry = IDL.Record({
    'amountMl' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const DailyTrackingSummary = IDL.Record({
    'date' : DateKey,
    'lastUpdated' : Timestamp,
    'waterEntries' : IDL.Vec(WaterEntry),
    'steps' : IDL.Nat,
    'totalWaterMl' : IDL.Nat,
    'waterGoalMl' : IDL.Nat,
  });
  const FlexibilityLevel = IDL.Nat;
  const FitnessTrack = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'principal' : IDL.Principal,
    'heightCm' : IDL.Float64,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'weightKg' : IDL.Float64,
    'flexibilityLevel' : FlexibilityLevel,
    'dietaryRestrictions' : IDL.Text,
    'fitnessTrack' : FitnessTrack,
    'phone' : IDL.Text,
    'healthIssues' : IDL.Text,
  });
  const UserProgress = IDL.Record({
    'completedDays' : IDL.Vec(IDL.Nat),
    'principal' : IDL.Principal,
    'lastCompletedDay' : IDL.Opt(IDL.Nat),
    'fitnessTrack' : FitnessTrack,
    'isDeveloper' : IDL.Bool,
  });
  const DailyStepCount = IDL.Record({
    'date' : DateKey,
    'lastUpdated' : Timestamp,
    'steps' : IDL.Nat,
  });
  const ProfileInput = IDL.Record({
    'age' : IDL.Nat,
    'heightCm' : IDL.Float64,
    'email' : IDL.Text,
    'weightKg' : IDL.Float64,
    'flexibilityLevel' : FlexibilityLevel,
    'dietaryRestrictions' : IDL.Text,
    'phone' : IDL.Text,
    'healthIssues' : IDL.Text,
  });
  
  return IDL.Service({
    'addWaterEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'clearLastWaterEntry' : IDL.Func([IDL.Text], [], []),
    'getAllDayPlans' : IDL.Func([], [IDL.Vec(DayPlan)], ['query']),
    'getDailyTrackingSummary' : IDL.Func(
        [IDL.Text],
        [DailyTrackingSummary],
        ['query'],
      ),
    'getDayPlan' : IDL.Func([IDL.Nat], [IDL.Opt(DayPlan)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyProgress' : IDL.Func([], [UserProgress], ['query']),
    'getStepCount' : IDL.Func([IDL.Text], [DailyStepCount], ['query']),
    'getWaterIntake' : IDL.Func([IDL.Text], [DailyTrackingSummary], ['query']),
    'hasCompletedOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
    'markDayComplete' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveProfile' : IDL.Func([ProfileInput], [UserProfile], []),
    'saveStepCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setDeveloperMode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };