/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyStepCount {
  'date' : DateKey,
  'lastUpdated' : Timestamp,
  'steps' : bigint,
}
export interface DailyTrackingSummary {
  'date' : DateKey,
  'lastUpdated' : Timestamp,
  'waterEntries' : Array<WaterEntry>,
  'steps' : bigint,
  'totalWaterMl' : bigint,
  'waterGoalMl' : bigint,
}
export type DateKey = string;
export interface DayPlan {
  'day' : bigint,
  'focus' : string,
  'meals' : Array<Meal>,
  'title' : string,
  'exercises' : Array<Exercise>,
}
export interface Exercise {
  'difficulty' : string,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'description' : string,
  'instructions' : string,
  'durationSec' : bigint,
}
export type FitnessTrack = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type FlexibilityLevel = bigint;
export interface Macros {
  'fatG' : bigint,
  'calories' : bigint,
  'carbsG' : bigint,
  'proteinG' : bigint,
}
export interface Meal {
  'prepTimeMins' : bigint,
  'name' : string,
  'instructions' : Array<string>,
  'macros' : Macros,
  'servings' : bigint,
  'ingredients' : Array<string>,
  'mealType' : MealType,
}
export type MealType = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snack' : null } |
  { 'dinner' : null };
export interface ProfileInput {
  'age' : bigint,
  'heightCm' : number,
  'email' : string,
  'weightKg' : number,
  'flexibilityLevel' : FlexibilityLevel,
  'dietaryRestrictions' : string,
  'phone' : string,
  'healthIssues' : string,
}
export type Timestamp = bigint;
export interface UserProfile {
  'age' : bigint,
  'principal' : Principal,
  'heightCm' : number,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'weightKg' : number,
  'flexibilityLevel' : FlexibilityLevel,
  'dietaryRestrictions' : string,
  'fitnessTrack' : FitnessTrack,
  'phone' : string,
  'healthIssues' : string,
}
export interface UserProgress {
  'completedDays' : Array<bigint>,
  'principal' : Principal,
  'lastCompletedDay' : [] | [bigint],
  'fitnessTrack' : FitnessTrack,
  'isDeveloper' : boolean,
}
export interface WaterEntry { 'amountMl' : bigint, 'timestamp' : Timestamp }
export interface _SERVICE {
  'addWaterEntry' : ActorMethod<[string, bigint], undefined>,
  'clearLastWaterEntry' : ActorMethod<[string], undefined>,
  'getAllDayPlans' : ActorMethod<[], Array<DayPlan>>,
  'getDailyTrackingSummary' : ActorMethod<[string], DailyTrackingSummary>,
  'getDayPlan' : ActorMethod<[bigint], [] | [DayPlan]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyProgress' : ActorMethod<[], UserProgress>,
  'getStepCount' : ActorMethod<[string], DailyStepCount>,
  'getWaterIntake' : ActorMethod<[string], DailyTrackingSummary>,
  'hasCompletedOnboarding' : ActorMethod<[], boolean>,
  'markDayComplete' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveProfile' : ActorMethod<[ProfileInput], UserProfile>,
  'saveStepCount' : ActorMethod<[string, bigint], undefined>,
  'setDeveloperMode' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];