/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    prepTimeMins: bigint;
    name: string;
    instructions: Array<string>;
    macros: Macros;
    servings: bigint;
    ingredients: Array<string>;
    mealType: MealType;
}
export interface Exercise {
    difficulty: string;
    name: string;
    reps: bigint;
    sets: bigint;
    description: string;
    instructions: string;
    durationSec: bigint;
}
export type Timestamp = bigint;
export type DateKey = string;
export type FlexibilityLevel = bigint;
export interface DailyStepCount {
    date: DateKey;
    lastUpdated: Timestamp;
    steps: bigint;
}
export interface UserProgress {
    completedDays: Array<bigint>;
    principal: Principal;
    lastCompletedDay?: bigint;
    fitnessTrack: FitnessTrack;
    isDeveloper: boolean;
}
export interface DayPlan {
    day: bigint;
    focus: string;
    meals: Array<Meal>;
    title: string;
    exercises: Array<Exercise>;
}
export interface WaterEntry {
    amountMl: bigint;
    timestamp: Timestamp;
}
export interface Macros {
    fatG: bigint;
    calories: bigint;
    carbsG: bigint;
    proteinG: bigint;
}
export interface DailyTrackingSummary {
    date: DateKey;
    lastUpdated: Timestamp;
    waterEntries: Array<WaterEntry>;
    steps: bigint;
    totalWaterMl: bigint;
    waterGoalMl: bigint;
}
export interface UserProfile {
    age: bigint;
    principal: Principal;
    heightCm: number;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    weightKg: number;
    flexibilityLevel: FlexibilityLevel;
    dietaryRestrictions: string;
    fitnessTrack: FitnessTrack;
    phone: string;
    healthIssues: string;
}
export interface ProfileInput {
    age: bigint;
    heightCm: number;
    email: string;
    weightKg: number;
    flexibilityLevel: FlexibilityLevel;
    dietaryRestrictions: string;
    phone: string;
    healthIssues: string;
}
export enum FitnessTrack {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum MealType {
    breakfast = "breakfast",
    lunch = "lunch",
    snack = "snack",
    dinner = "dinner"
}
export interface backendInterface {
    addWaterEntry(date: string, amountMl: bigint): Promise<void>;
    clearLastWaterEntry(date: string): Promise<void>;
    getAllDayPlans(): Promise<Array<DayPlan>>;
    getDailyTrackingSummary(date: string): Promise<DailyTrackingSummary>;
    getDayPlan(day: bigint): Promise<DayPlan | null>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyProgress(): Promise<UserProgress>;
    getStepCount(date: string): Promise<DailyStepCount>;
    getWaterIntake(date: string): Promise<DailyTrackingSummary>;
    hasCompletedOnboarding(): Promise<boolean>;
    markDayComplete(day: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveProfile(input: ProfileInput): Promise<UserProfile>;
    saveStepCount(date: string, steps: bigint): Promise<void>;
    setDeveloperMode(code: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { DayPlan as _DayPlan, Exercise as _Exercise, FitnessTrack as _FitnessTrack, FlexibilityLevel as _FlexibilityLevel, Macros as _Macros, Meal as _Meal, MealType as _MealType, Timestamp as _Timestamp, UserProfile as _UserProfile, UserProgress as _UserProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addWaterEntry(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWaterEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWaterEntry(arg0, arg1);
            return result;
        }
    }
    async clearLastWaterEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLastWaterEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLastWaterEntry(arg0);
            return result;
        }
    }
    async getAllDayPlans(): Promise<Array<DayPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDayPlans();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDayPlans();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyTrackingSummary(arg0: string): Promise<DailyTrackingSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTrackingSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTrackingSummary(arg0);
            return result;
        }
    }
    async getDayPlan(arg0: bigint): Promise<DayPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayPlan(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayPlan(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress();
                return from_candid_UserProgress_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress();
            return from_candid_UserProgress_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStepCount(arg0: string): Promise<DailyStepCount> {
        if (this.processError) {
            try {
                const result = await this.actor.getStepCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStepCount(arg0);
            return result;
        }
    }
    async getWaterIntake(arg0: string): Promise<DailyTrackingSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaterIntake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaterIntake(arg0);
            return result;
        }
    }
    async hasCompletedOnboarding(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCompletedOnboarding();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCompletedOnboarding();
            return result;
        }
    }
    async markDayComplete(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markDayComplete(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDayComplete(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProfile(arg0: ProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0);
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0);
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveStepCount(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStepCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStepCount(arg0, arg1);
            return result;
        }
    }
    async setDeveloperMode(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setDeveloperMode(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDeveloperMode(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DayPlan_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayPlan): DayPlan {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessTrack_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessTrack): FitnessTrack {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MealType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealType): MealType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Meal_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Meal): Meal {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProgress_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DayPlan]): DayPlan | null {
    return value.length === 0 ? null : from_candid_DayPlan_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    principal: Principal;
    heightCm: number;
    createdAt: _Timestamp;
    email: string;
    updatedAt: _Timestamp;
    weightKg: number;
    flexibilityLevel: _FlexibilityLevel;
    dietaryRestrictions: string;
    fitnessTrack: _FitnessTrack;
    phone: string;
    healthIssues: string;
}): {
    age: bigint;
    principal: Principal;
    heightCm: number;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    weightKg: number;
    flexibilityLevel: FlexibilityLevel;
    dietaryRestrictions: string;
    fitnessTrack: FitnessTrack;
    phone: string;
    healthIssues: string;
} {
    return {
        age: value.age,
        principal: value.principal,
        heightCm: value.heightCm,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        weightKg: value.weightKg,
        flexibilityLevel: value.flexibilityLevel,
        dietaryRestrictions: value.dietaryRestrictions,
        fitnessTrack: from_candid_FitnessTrack_n13(_uploadFile, _downloadFile, value.fitnessTrack),
        phone: value.phone,
        healthIssues: value.healthIssues
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedDays: Array<bigint>;
    principal: Principal;
    lastCompletedDay: [] | [bigint];
    fitnessTrack: _FitnessTrack;
    isDeveloper: boolean;
}): {
    completedDays: Array<bigint>;
    principal: Principal;
    lastCompletedDay?: bigint;
    fitnessTrack: FitnessTrack;
    isDeveloper: boolean;
} {
    return {
        completedDays: value.completedDays,
        principal: value.principal,
        lastCompletedDay: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.lastCompletedDay)),
        fitnessTrack: from_candid_FitnessTrack_n13(_uploadFile, _downloadFile, value.fitnessTrack),
        isDeveloper: value.isDeveloper
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: bigint;
    focus: string;
    meals: Array<_Meal>;
    title: string;
    exercises: Array<_Exercise>;
}): {
    day: bigint;
    focus: string;
    meals: Array<Meal>;
    title: string;
    exercises: Array<Exercise>;
} {
    return {
        day: value.day,
        focus: value.focus,
        meals: from_candid_vec_n4(_uploadFile, _downloadFile, value.meals),
        title: value.title,
        exercises: value.exercises
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prepTimeMins: bigint;
    name: string;
    instructions: Array<string>;
    macros: _Macros;
    servings: bigint;
    ingredients: Array<string>;
    mealType: _MealType;
}): {
    prepTimeMins: bigint;
    name: string;
    instructions: Array<string>;
    macros: Macros;
    servings: bigint;
    ingredients: Array<string>;
    mealType: MealType;
} {
    return {
        prepTimeMins: value.prepTimeMins,
        name: value.name,
        instructions: value.instructions,
        macros: value.macros,
        servings: value.servings,
        ingredients: value.ingredients,
        mealType: from_candid_MealType_n7(_uploadFile, _downloadFile, value.mealType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): FitnessTrack {
    return "intermediate" in value ? FitnessTrack.intermediate : "beginner" in value ? FitnessTrack.beginner : "advanced" in value ? FitnessTrack.advanced : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
}): MealType {
    return "breakfast" in value ? MealType.breakfast : "lunch" in value ? MealType.lunch : "snack" in value ? MealType.snack : "dinner" in value ? MealType.dinner : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DayPlan>): Array<DayPlan> {
    return value.map((x)=>from_candid_DayPlan_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Meal>): Array<Meal> {
    return value.map((x)=>from_candid_Meal_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
